// Copyright (c) Microsoft. All rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Iot.IotCoreAppDeployment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Iot.IotCoreAppDeployment.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument ({0}) requires input..
        /// </summary>
        internal static string CommandLineParser_ArgRequiresInput {
            get {
                return ResourceManager.GetString("CommandLineParser_ArgRequiresInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Optional arguments requiring no input: -arg .
        /// </summary>
        internal static string CommandLineParser_OptionalArgNoInput {
            get {
                return ResourceManager.GetString("CommandLineParser_OptionalArgNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Optional arguments requiring input: -arg value.
        /// </summary>
        internal static string CommandLineParser_OptionalArgWithInput {
            get {
                return ResourceManager.GetString("CommandLineParser_OptionalArgWithInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Required arguments requiring input: -arg value.
        /// </summary>
        internal static string CommandLineParser_RequiredArgWithInput {
            get {
                return ResourceManager.GetString("CommandLineParser_RequiredArgWithInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument ({0}) was not recognized.  See usage:.
        /// </summary>
        internal static string CommandLineParser_UnrecognizedArgument {
            get {
                return ResourceManager.GetString("CommandLineParser_UnrecognizedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... APPX file created.
        /// </summary>
        internal static string DeploymentWorker_AppxCreated {
            get {
                return ResourceManager.GetString("DeploymentWorker_AppxCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... APPX map file created: {0}.
        /// </summary>
        internal static string DeploymentWorker_AppxMapCreated {
            get {
                return ResourceManager.GetString("DeploymentWorker_AppxMapCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... APPX file signed with PFX.
        /// </summary>
        internal static string DeploymentWorker_AppxSignedWithPfx {
            get {
                return ResourceManager.GetString("DeploymentWorker_AppxSignedWithPfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the target architecture [ARM|X86] ... ARM is default.
        /// </summary>
        internal static string DeploymentWorker_ArchArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_ArchArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported configuration.
        /// </summary>
        internal static string DeploymentWorker_argumentHelper_0_is_not_a_supported_configuration {
            get {
                return ResourceManager.GetString("DeploymentWorker_argumentHelper_0_is_not_a_supported_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported target architecture.
        /// </summary>
        internal static string DeploymentWorker_argumentHelper_0_is_not_a_supported_target_architecture {
            get {
                return ResourceManager.GetString("DeploymentWorker_argumentHelper_0_is_not_a_supported_target_architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... build failed.
        /// </summary>
        internal static string DeploymentWorker_BuildFailed {
            get {
                return ResourceManager.GetString("DeploymentWorker_BuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... build started.
        /// </summary>
        internal static string DeploymentWorker_BuildStarted {
            get {
                return ResourceManager.GetString("DeploymentWorker_BuildStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... build succeeded.
        /// </summary>
        internal static string DeploymentWorker_BuildSucceeded {
            get {
                return ResourceManager.GetString("DeploymentWorker_BuildSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DeploymentWorker_Cancel {
            get {
                return ResourceManager.GetString("DeploymentWorker_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... project files tailored to current deployment..
        /// </summary>
        internal static string DeploymentWorker_ChangedAppxManifest {
            get {
                return ResourceManager.GetString("DeploymentWorker_ChangedAppxManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the configuration [Debug|Release] ... Debug is default.
        /// </summary>
        internal static string DeploymentWorker_ConfigArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_ConfigArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... base project files found and copied: {0}.
        /// </summary>
        internal static string DeploymentWorker_CopiedBaseFromResourcesMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_CopiedBaseFromResourcesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... dependencies copied into place.
        /// </summary>
        internal static string DeploymentWorker_CopiedDependencyAppxFiles {
            get {
                return ResourceManager.GetString("DeploymentWorker_CopiedDependencyAppxFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... project files found and copied: {0}.
        /// </summary>
        internal static string DeploymentWorker_CopiedFromResourcesMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_CopiedFromResourcesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... CER file generated from PFX.
        /// </summary>
        internal static string DeploymentWorker_CreatedCertFromPfx {
            get {
                return ResourceManager.GetString("DeploymentWorker_CreatedCertFromPfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         logfile: {0}.
        /// </summary>
        internal static string DeploymentWorker_CreatedLogfile {
            get {
                return ResourceManager.GetString("DeploymentWorker_CreatedLogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string DeploymentWorker_CustomPassword {
            get {
                return ResourceManager.GetString("DeploymentWorker_CustomPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string DeploymentWorker_CustomUsername {
            get {
                return ResourceManager.GetString("DeploymentWorker_CustomUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... starting to deploy certificate, APPX, and dependencies.
        /// </summary>
        internal static string DeploymentWorker_DeployAppx_starting_to_deploy_certificate_APPX_and_dependencies {
            get {
                return ResourceManager.GetString("DeploymentWorker_DeployAppx_starting_to_deploy_certificate_APPX_and_dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... deployment {0} failed..
        /// </summary>
        internal static string DeploymentWorker_DeployFailed {
            get {
                return ResourceManager.GetString("DeploymentWorker_DeployFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... deployment {0} finished..
        /// </summary>
        internal static string DeploymentWorker_DeployFinished {
            get {
                return ResourceManager.GetString("DeploymentWorker_DeployFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... device specified ({0}) cannot be resolved: {1}.
        /// </summary>
        internal static string DeploymentWorker_DeviceNotFound {
            get {
                return ResourceManager.GetString("DeploymentWorker_DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Custom Credentials.
        /// </summary>
        internal static string DeploymentWorker_EnterCustomCredentials {
            get {
                return ResourceManager.GetString("DeploymentWorker_EnterCustomCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add all capabilities to AppxManifest.xml..
        /// </summary>
        internal static string DeploymentWorker_FailedToAddCapability {
            get {
                return ResourceManager.GetString("DeploymentWorker_FailedToAddCapability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to make all changes to AppxManifest.xml..
        /// </summary>
        internal static string DeploymentWorker_FailedToChangeAppxManifest {
            get {
                return ResourceManager.GetString("DeploymentWorker_FailedToChangeAppxManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy {0} to {1}.
        /// </summary>
        internal static string DeploymentWorker_FailedToCopy0to1 {
            get {
                return ResourceManager.GetString("DeploymentWorker_FailedToCopy0to1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get {0} from resources..
        /// </summary>
        internal static string DeploymentWorker_FailedToCopyFromResourcesMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_FailedToCopyFromResourcesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the project appx map contents..
        /// </summary>
        internal static string DeploymentWorker_FailedToGetProjectContents {
            get {
                return ResourceManager.GetString("DeploymentWorker_FailedToGetProjectContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the template appx map contents..
        /// </summary>
        internal static string DeploymentWorker_FailedToGetTemplateContents {
            get {
                return ResourceManager.GetString("DeploymentWorker_FailedToGetTemplateContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy dependency to {0}.
        /// </summary>
        internal static string DeploymentWorker_FailedToSaveAppx {
            get {
                return ResourceManager.GetString("DeploymentWorker_FailedToSaveAppx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... base project system found: {0}.
        /// </summary>
        internal static string DeploymentWorker_FoundBaseProjectType {
            get {
                return ResourceManager.GetString("DeploymentWorker_FoundBaseProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... project system found: {0}.
        /// </summary>
        internal static string DeploymentWorker_FoundProjectForSource {
            get {
                return ResourceManager.GetString("DeploymentWorker_FoundProjectForSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter target name or ip address: .
        /// </summary>
        internal static string DeploymentWorker_GetTargetFromUser {
            get {
                return ResourceManager.GetString("DeploymentWorker_GetTargetFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Target.
        /// </summary>
        internal static string DeploymentWorker_GetTargetFromUserTitle {
            get {
                return ResourceManager.GetString("DeploymentWorker_GetTargetFromUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display usage message.
        /// </summary>
        internal static string DeploymentWorker_HelpArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_HelpArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is specified, the temp folder will not be deleted.
        /// </summary>
        internal static string DeploymentWorker_KeepTempArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_KeepTempArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify MakeAppx.exe full path ... if not provided, registry is queried.
        /// </summary>
        internal static string DeploymentWorker_MakeAppxArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_MakeAppxArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: base project type is not supported. {0}.
        /// </summary>
        internal static string DeploymentWorker_NoBaseProjectType {
            get {
                return ResourceManager.GetString("DeploymentWorker_NoBaseProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: source is not supported. {0}.
        /// </summary>
        internal static string DeploymentWorker_NoProjectForSource {
            get {
                return ResourceManager.GetString("DeploymentWorker_NoProjectForSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DeploymentWorker_Ok {
            get {
                return ResourceManager.GetString("DeploymentWorker_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify PowerShell.exe full path ... if not provided, registry is queried.
        /// </summary>
        internal static string DeploymentWorker_PowershellArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_PowershellArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: PowerShell.exe cannot be found.  Please use -powershell to provide.
        /// </summary>
        internal static string DeploymentWorker_PowershellNotFound1 {
            get {
                return ResourceManager.GetString("DeploymentWorker_PowershellNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        the location..
        /// </summary>
        internal static string DeploymentWorker_PowershellNotFound2 {
            get {
                return ResourceManager.GetString("DeploymentWorker_PowershellNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... previous installation {0} was not uninstalled (if it wasn&apos;t previously installed, this is expected).
        /// </summary>
        internal static string DeploymentWorker_PreviousDeployNotUninstalled {
            get {
                return ResourceManager.GetString("DeploymentWorker_PreviousDeployNotUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... previously deployed {0} uninstalled successfully.
        /// </summary>
        internal static string DeploymentWorker_PreviousDeployUninstalled {
            get {
                return ResourceManager.GetString("DeploymentWorker_PreviousDeployUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify local path to save APPX in ... if not provided, files will not be saved.
        /// </summary>
        internal static string DeploymentWorker_SaveAppxArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_SaveAppxArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify SDK version ... {0} is default.
        /// </summary>
        internal static string DeploymentWorker_SdkArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_SdkArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify SignTool.exe full path ... if not provided, registry is queried.
        /// </summary>
        internal static string DeploymentWorker_SignToolArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_SignToolArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify source input.
        /// </summary>
        internal static string DeploymentWorker_SourceArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_SourceArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... deploying to target {0}.
        /// </summary>
        internal static string DeploymentWorker_StartDeploy {
            get {
                return ResourceManager.GetString("DeploymentWorker_StartDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting utility to deploy an Iot Core app based on source ....
        /// </summary>
        internal static string DeploymentWorker_Starting {
            get {
                return ResourceManager.GetString("DeploymentWorker_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: suported dependency sdks are: {0}.
        /// </summary>
        internal static string DeploymentWorker_SupportedSdksErrorMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_SupportedSdksErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speficy IoT Core device name or IP address.
        /// </summary>
        internal static string DeploymentWorker_TargetArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_TargetArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... device must be specified..
        /// </summary>
        internal static string DeploymentWorker_TargetMissing {
            get {
                return ResourceManager.GetString("DeploymentWorker_TargetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify target user password) ... {0} is default.
        /// </summary>
        internal static string DeploymentWorker_TargetPasswordArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_TargetPasswordArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify target username ... {0} is default.
        /// </summary>
        internal static string DeploymentWorker_TargetUserNameArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_TargetUserNameArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the temp working directory ... if not specified, %temp% will be used.
        /// </summary>
        internal static string DeploymentWorker_TempDirArgMsg {
            get {
                return ResourceManager.GetString("DeploymentWorker_TempDirArgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: MakeAppx.exe and SignTool.exe must be installed.  These tools .
        /// </summary>
        internal static string DeploymentWorker_ToolNotFound1 {
            get {
                return ResourceManager.GetString("DeploymentWorker_ToolNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        are installed as part of the Windows Standalone SDK for Windows 10 .
        /// </summary>
        internal static string DeploymentWorker_ToolNotFound2 {
            get {
                return ResourceManager.GetString("DeploymentWorker_ToolNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        (https://go.microsoft.com/fwlink/?LinkID=698771).  If they are .
        /// </summary>
        internal static string DeploymentWorker_ToolNotFound3 {
            get {
                return ResourceManager.GetString("DeploymentWorker_ToolNotFound3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        present on your machine, please provide the paths using -makeappx .
        /// </summary>
        internal static string DeploymentWorker_ToolNotFound4 {
            get {
                return ResourceManager.GetString("DeploymentWorker_ToolNotFound4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        and -signtool..
        /// </summary>
        internal static string DeploymentWorker_ToolNotFound5 {
            get {
                return ResourceManager.GetString("DeploymentWorker_ToolNotFound5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... deployment request unauthorized using these credentials: {0} {1}.
        /// </summary>
        internal static string DeploymentWorker_UnauthorizedDeployment {
            get {
                return ResourceManager.GetString("DeploymentWorker_UnauthorizedDeployment", resourceCulture);
            }
        }
    }
}
