// Copyright (c) Microsoft. All rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Iot.Ino {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Iot.Ino.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy microsoft.iot.sdkfromarduino.1.1.1.nupkg from resources and unzip it.
        /// </summary>
        internal static string InoProject_ArduinoNupkgFailure {
            get {
                return ResourceManager.GetString("InoProject_ArduinoNupkgFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... failed to compile dependency source code..
        /// </summary>
        internal static string InoProject_CompilationFailure {
            get {
                return ResourceManager.GetString("InoProject_CompilationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compile {0} to {1}..
        /// </summary>
        internal static string InoProject_CompileFailed {
            get {
                return ResourceManager.GetString("InoProject_CompileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler cannot be found. {0}.
        /// </summary>
        internal static string InoProject_CompilerNotFound {
            get {
                return ResourceManager.GetString("InoProject_CompilerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...compile step failed!.
        /// </summary>
        internal static string InoProject_CompileStepFailed {
            get {
                return ResourceManager.GetString("InoProject_CompileStepFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... failed to compile {0}..
        /// </summary>
        internal static string InoProject_FileCompilationFailure {
            get {
                return ResourceManager.GetString("InoProject_FileCompilationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy microsoft.iot.lightning.1.0.2-alpha.nupkg from resources and unzip it.
        /// </summary>
        internal static string InoProject_LightningNupkgFailure {
            get {
                return ResourceManager.GetString("InoProject_LightningNupkgFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker cannot be found. {0}.
        /// </summary>
        internal static string InoProject_LinkerNotFound {
            get {
                return ResourceManager.GetString("InoProject_LinkerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... linking step failed!.
        /// </summary>
        internal static string InoProject_LinkStepFailed {
            get {
                return ResourceManager.GetString("InoProject_LinkStepFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy pch.h from resources.
        /// </summary>
        internal static string InoProject_PchFailure {
            get {
                return ResourceManager.GetString("InoProject_PchFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK cannot be found..
        /// </summary>
        internal static string InoProject_SdkNotFound {
            get {
                return ResourceManager.GetString("InoProject_SdkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy StartupTask.cpp from resources.
        /// </summary>
        internal static string InoProject_StartupTaskFailure {
            get {
                return ResourceManager.GetString("InoProject_StartupTaskFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC Include files cannot be found..
        /// </summary>
        internal static string InoProject_VcIncludesNotFound {
            get {
                return ResourceManager.GetString("InoProject_VcIncludesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC library files cannot be found..
        /// </summary>
        internal static string InoProject_VcLibsNotFound {
            get {
                return ResourceManager.GetString("InoProject_VcLibsNotFound", resourceCulture);
            }
        }
    }
}
